version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - er-network

  personaje-service:
    build:
      context: .
    container_name: personaje-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/personajes
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mongo
    networks:
      - er-network

volumes:
  mongodb_data:

networks:
  er-network:
